apiVersion: apps/v1
kind: Deployment
metadata:
  name: frontend
  namespace: expense
  labels:
    app: frontend
    tier: web
    project: expense
spec:
  replicas: 2
  selector:
    matchLabels:
      app: frontend
      tier: web
      project: expense
  template:
    metadata:
      labels:
        app: frontend
        tier: web
        project: expense
    spec:
      containers:
      - name: frontend
        image: mohansai7/frontend:v1
---
apiVersion: v1
kind: Service
metadata:
  name: frontend-svc
  namespace: expense
spec:
  type: LoadBalancer  #by default it will create classic load balancer, if ingress is introduced then it will create Application Load Balancer.
  selector:
    app: frontend
    tier: web
    project: expense
  ports:
  - name: frontend-svc-port
    protocol: TCP
    port: 80
    targetPort: 80