apiVersion: storage.k8s.io/v1
kind: StorageClass
metadata:
  name: expense-ebs
  #namespace: expense
provisioner: ebs.csi.aws.com
reclaimPolicy: Retain
volumeBindingMode: WaitForFirstConsumer  #volume will get created when pod is getting created.


