apiVersion: v1
kind: ConfigMap
metadata:
  name: backend
  namespace: expense
  
data:
  DB_HOST: mysql

---

apiVersion: apps/v1
kind: Deployment
metadata:
  name: backend
  namespace: expense
  labels:
    app: backend
    tier: app
    project: expense
spec:
  replicas: 2
  selector:
    matchLabels:
      app: backend
      tier: app
      project: expense
  templates:
    metadata:
      labels:
        app: backend
        tier: app
        project: expense
    spec:
      containers:
      - name: backend
        image: mohansai7/backend:v1
        envFrom:
        - configMapRef:
            name: backend

---
apiVersion: v1
kind: Service
metadata:
  name: backend-svc
  namespace: expense
spec:
  type: LoadBalancer
  selector:
    app: backend
    tier: app
    project: expense
  ports:
  - name: backend-svc-port
    protocol: TCP
    port: 8080
    targetPort: 8080
      
